{{- if .Values.application.create }}
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: {{ .Release.Name }}
  componentKinds:
    - group: core
      kind: Service
    - group: core
      kind: Secret
    - group: core
      kind: ConfigMap
    - group: apps
      kind: StatefulSet
  assemblyPhase: "Succeeded"
  descriptor:
    version: {{ .Chart.AppVersion }}
    description: {{ .Chart.Description }}
    icons:
      - src: "https://example.com/mariadb.png"
        type: "image/png"
    type: "mariadb"
    maintainers:
      {{- range .Chart.Maintainers }}
      - name: {{ .Name }}
        email: {{ .Email }}
      {{- end }}
    owners:
      {{- range .Chart.Maintainers }}
      - "{{ .Name }} {{ .Email }}"
      {{- end }}
    keywords:
      {{- range $value := .Chart.Keywords }}
      - {{ $value | quote }}
      {{- end }}
    links:
      - description: About
        url: "https://mariadb.org/"
{{- end }}
