apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "master.fullname" . }}-init-scripts
  labels:
    app: {{ template "mariadb.name" . }}
    component: "master"
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- if .Values.application.tag }}
    app.kubernetes.io/name: {{ .Release.Name }}
    {{- end }}
data:
{{ (.Files.Glob "files/docker-entrypoint-initdb.d/*").AsConfig | indent 2 }}
